-- Portable PostgreSQL schema for the built-in crawler. Runtime behavior lives in
-- the application and does not depend on Supabase RLS, Auth, Data API, or RPC.
create schema if not exists crawler;

create table if not exists crawler.candidate (
  id bigint generated by default as identity primary key,
  url text not null,
  canonical_url text not null unique,
  domain text not null,
  source text not null,
  source_item_id text,
  source_url text,
  status text not null default 'pending'
    check (status in ('pending', 'processing', 'review', 'published', 'retry', 'failed', 'rejected')),
  attempt_count integer not null default 0,
  next_retry_at timestamp with time zone,
  locked_at timestamp with time zone,
  title text,
  description text,
  detail text,
  image_url text,
  category_name text,
  error_message text,
  discovered_at timestamp with time zone not null default now(),
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create index if not exists candidate_claimable_idx
  on crawler.candidate (status, next_retry_at, discovered_at)
  where status in ('pending', 'retry', 'processing');

create index if not exists candidate_source_item_idx
  on crawler.candidate (source, source_item_id)
  where source_item_id is not null;

create unique index if not exists web_navigation_url_unique_idx
  on public.web_navigation (url)
  where url is not null;
