create table if not exists public.crawl_candidate (
  id bigint generated by default as identity primary key,
  url text not null,
  canonical_url text not null unique,
  domain text not null,
  source text not null,
  source_item_id text,
  source_url text,
  status text not null default 'pending'
    check (status in ('pending', 'processing', 'review', 'published', 'retry', 'failed', 'rejected')),
  attempt_count integer not null default 0,
  next_retry_at timestamp with time zone,
  locked_at timestamp with time zone,
  title text,
  description text,
  detail text,
  image_url text,
  category_name text,
  error_message text,
  discovered_at timestamp with time zone not null default now(),
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create index if not exists crawl_candidate_claimable_idx
  on public.crawl_candidate (status, next_retry_at, discovered_at)
  where status in ('pending', 'retry', 'processing');

create index if not exists crawl_candidate_source_item_idx
  on public.crawl_candidate (source, source_item_id)
  where source_item_id is not null;

alter table public.crawl_candidate enable row level security;
revoke all on table public.crawl_candidate from public, anon, authenticated;
grant select, insert, update on table public.crawl_candidate to anon, authenticated;
grant usage, select on sequence public.crawl_candidate_id_seq to anon, authenticated;

drop policy if exists "Public crawler access" on public.crawl_candidate;
drop policy if exists "Public can read crawler candidates" on public.crawl_candidate;
drop policy if exists "Public can insert crawler candidates" on public.crawl_candidate;
drop policy if exists "Public can update crawler candidates" on public.crawl_candidate;

create policy "Public can read crawler candidates"
  on public.crawl_candidate
  for select
  to anon, authenticated
  using (true);

create policy "Public can insert crawler candidates"
  on public.crawl_candidate
  for insert
  to anon, authenticated
  with check (true);

create policy "Public can update crawler candidates"
  on public.crawl_candidate
  for update
  to anon, authenticated
  using (true)
  with check (true);

create or replace function public.claim_crawl_candidates(batch_size integer default 5)
returns setof public.crawl_candidate
language sql
security invoker
set search_path = public
as $$
  with picked as (
    select id
    from public.crawl_candidate
    where
      status = 'pending'
      or (status = 'retry' and coalesce(next_retry_at, now()) <= now())
      or (status = 'processing' and locked_at < now() - interval '15 minutes')
    order by discovered_at asc
    limit greatest(1, least(batch_size, 20))
    for update skip locked
  )
  update public.crawl_candidate as candidate
  set
    status = 'processing',
    locked_at = now(),
    attempt_count = candidate.attempt_count + 1,
    updated_at = now(),
    error_message = null
  from picked
  where candidate.id = picked.id
  returning candidate.*;
$$;

revoke all on function public.claim_crawl_candidates(integer) from public;
grant execute on function public.claim_crawl_candidates(integer) to anon, authenticated;

create unique index if not exists web_navigation_url_unique_idx
  on public.web_navigation (url)
  where url is not null;

create or replace function public.review_crawl_candidate(
  candidate_id bigint,
  review_action text,
  category_override text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  candidate public.crawl_candidate%rowtype;
  published_name text;
  selected_category text;
begin
  if review_action not in ('approve', 'reject') then
    raise exception using errcode = '22023', message = 'invalid_review_action';
  end if;

  select * into candidate
  from public.crawl_candidate
  where id = candidate_id and status = 'review'
  for update;

  if not found then
    raise exception using errcode = 'P0001', message = 'candidate_not_reviewable';
  end if;

  if review_action = 'reject' then
    update public.crawl_candidate
    set status = 'rejected', updated_at = now()
    where id = candidate.id;

    if candidate.source = 'submission' then
      update public.submit set status = 2 where id = candidate.source_item_id::bigint;
    end if;

    return jsonb_build_object('status', 'rejected');
  end if;

  if candidate.title is null or candidate.description is null or candidate.detail is null then
    raise exception using errcode = '23514', message = 'candidate_content_incomplete';
  end if;

  selected_category := coalesce(category_override, candidate.category_name, 'other');
  published_name := regexp_replace(lower(regexp_replace(candidate.domain, '^www\.', '')), '[^a-z0-9]+', '-', 'g');
  published_name := trim(both '-' from published_name) || '-' || candidate.id::text;

  insert into public.web_navigation (
    name, title, content, detail, url, image_url, thumbnail_url,
    collection_time, tag_name, category_name
  ) values (
    published_name, candidate.title, candidate.description, candidate.detail,
    candidate.canonical_url, candidate.image_url, candidate.image_url,
    now(), selected_category, selected_category
  )
  on conflict (url) where url is not null do update set
    title = excluded.title,
    content = excluded.content,
    detail = excluded.detail,
    image_url = excluded.image_url,
    thumbnail_url = excluded.thumbnail_url,
    collection_time = excluded.collection_time,
    tag_name = excluded.tag_name,
    category_name = excluded.category_name
  returning name into published_name;

  update public.crawl_candidate
  set status = 'published', updated_at = now()
  where id = candidate.id;

  if candidate.source = 'submission' then
    update public.submit set status = 1 where id = candidate.source_item_id::bigint;
  end if;

  return jsonb_build_object(
    'status', 'published',
    'name', published_name,
    'categoryName', selected_category
  );
end;
$$;

revoke all on function public.review_crawl_candidate(bigint, text, text) from public;
grant execute on function public.review_crawl_candidate(bigint, text, text) to anon, authenticated;

alter table public.submit enable row level security;

drop policy if exists "Public can submit pending websites" on public.submit;
create policy "Public can submit pending websites"
  on public.submit
  for insert
  to anon, authenticated
  with check (coalesce(status, 0) = 0 and coalesce(is_feature, 0) = 0);
