create table if not exists public.crawl_candidate (
  id bigint generated by default as identity primary key,
  url text not null,
  canonical_url text not null unique,
  domain text not null,
  source text not null,
  source_item_id text,
  source_url text,
  status text not null default 'pending'
    check (status in ('pending', 'processing', 'review', 'published', 'retry', 'failed', 'rejected')),
  attempt_count integer not null default 0,
  next_retry_at timestamp with time zone,
  locked_at timestamp with time zone,
  title text,
  description text,
  detail text,
  image_url text,
  category_name text,
  error_message text,
  discovered_at timestamp with time zone not null default now(),
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create index if not exists crawl_candidate_claimable_idx
  on public.crawl_candidate (status, next_retry_at, discovered_at)
  where status in ('pending', 'retry', 'processing');

create index if not exists crawl_candidate_source_item_idx
  on public.crawl_candidate (source, source_item_id)
  where source_item_id is not null;

alter table public.crawl_candidate enable row level security;
revoke all on table public.crawl_candidate from anon, authenticated;

create or replace function public.claim_crawl_candidates(batch_size integer default 5)
returns setof public.crawl_candidate
language sql
security invoker
set search_path = public
as $$
  with picked as (
    select id
    from public.crawl_candidate
    where
      status = 'pending'
      or (status = 'retry' and coalesce(next_retry_at, now()) <= now())
      or (status = 'processing' and locked_at < now() - interval '15 minutes')
    order by discovered_at asc
    limit greatest(1, least(batch_size, 20))
    for update skip locked
  )
  update public.crawl_candidate as candidate
  set
    status = 'processing',
    locked_at = now(),
    attempt_count = candidate.attempt_count + 1,
    updated_at = now(),
    error_message = null
  from picked
  where candidate.id = picked.id
  returning candidate.*;
$$;

revoke all on function public.claim_crawl_candidates(integer) from public, anon, authenticated;
grant execute on function public.claim_crawl_candidates(integer) to service_role;

alter table public.submit enable row level security;

drop policy if exists "Public can submit pending websites" on public.submit;
create policy "Public can submit pending websites"
  on public.submit
  for insert
  to anon, authenticated
  with check (coalesce(status, 0) = 0 and coalesce(is_feature, 0) = 0);
